//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Careers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int PositionId { get; set; }
        public int ResumeId { get; set; }
        public ApplicationStatus Status { get; set; }
        public System.DateTime AppliedOn { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Resume Resume { get; set; }
        public virtual User User { get; set; }
    }
}
