//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Careers.Models
{
    using System;
    
    public enum ApplicationStatus : int
    {
        New = 0,
        Contact = 1,
        Interview = 2,
        Hire = 3,
        Removed = 4,
        Reject = 5
    }
}
