//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Careers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume
    {
        public Resume()
        {
            this.Applications = new HashSet<Application>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public byte[] Document { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
